# Generated by Django 3.2.5 on 2021-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_catagory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=20),
        ),
    ]
