# Generated by Django 3.2.5 on 2021-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_net_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.CharField(max_length=120),
        ),
    ]
